### ISSUE TITLE
echo-chamber app does not work

### ISSUE THREAD

**Issue by AndrewHuntington** [stevekinney/cypress-examples#6]
Hello, I am getting the following error when trying to reach the echo chamber app:
![Screen Shot 2022-05-31 at 15 45 55](https://user-images.githubusercontent.com/17849865/171109948-666be655-fdf4-4378-9fb8-07272e9c8f55.png)

I also noticed the following in my terminal and browser console as well:

Terminal:
`Invalid `prisma.user.findMany()` invocation:

  The table `main.User` does not exist in the current database.
Error: 
Invalid `prisma.user.findMany()` invocation:

  The table `main.User` does not exist in the current database.
    at cb (/Users/andyh82/projects/tutorials/fe-masters/cypress-testing/cypress/node_modules/@prisma/client/runtime/index.js:38683:17)
    at async get (/Users/andyh82/projects/tutorials/fe-masters/cypress-testing/cypress/src/routes/echo-chamber/api/users.ts:5:16)
    at async render_endpoint (file:///Users/andyh82/projects/tutorials/fe-masters/cypress-testing/cypress/node_modules/@sveltejs/kit/dist/ssr.js:65:19)
    at async resolve (file:///Users/andyh82/projects/tutorials/fe-masters/cypress-testing/cypress/node_modules/@sveltejs/kit/dist/ssr.js:1716:10)
    at async Object.handle (/Users/andyh82/projects/tutorials/fe-masters/cypress-testing/cypress/src/hooks.ts:8:9)
    at async respond (file:///Users/andyh82/projects/tutorials/fe-masters/cypress-testing/cypress/node_modules/@sveltejs/kit/dist/ssr.js:1696:10)
    at async svelteKitMiddleware (file:///Users/andyh82/projects/tutorials/fe-masters/cypress-testing/cypress/node_modules/@sveltejs/kit/dist/chunks/index.js:4558:22)`

Console:
![Screen Shot 2022-05-31 at 15 47 49](https://user-images.githubusercontent.com/17849865/171109842-ac682388-e646-4a4e-80dd-73dfdb5bb789.png)

All the other routes/apps seem to work fine.

I don't know Svelte at all, so any help would be appreciated! Thanks!

**Comment by AndrewHuntington** [comment]
Never mind. I figured out it.

In case someone else has this same issue, try running
`npm run db:setup`
